name: untukmu_social_tools
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  app_links: ^6.4.0
  crypto: ^3.0.6
  dotted_border: ^3.0.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  http: ^1.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
